apiVersion: v1
kind: Pod
metadata:
  name: "nginx"
  namespace: default
  labels:
    app: "nginx"
spec:
  initContainers:
  - name: content
    image: curlimages/curl
    args:
      - https://www.sheldonbrown.com/web_sample1.html
      - '-o'
      - /usr/share/nginx/html/index.html
    volumeMounts:
      - name:  emptydir-volume
        mountPath: /usr/share/nginx/html
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: emptydir-volume
      mountPath: /usr/share/nginx/html
  volumes:
    - name: emptydir-volume
      emptyDir: {}
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30100