apiVersion: v1
kind: Pod
metadata:
  name: "hello-world"
  namespace: default
  labels:
    app: "hello-world"
spec:
  imagePullSecrets:
    - name: github-cred
  containers:
  - name: hello-world
    image: "ghcr.io/levelup-devops/hello-world-app:8"