apiVersion: v1
kind: Pod
metadata:
  name: "nginx"
  namespace: default
  labels:
    app: "nginx"
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: nginx-vol
      mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-vol
      persistentVolumeClaim:
        claimName: nginx
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi