pipeline {
    agent { label 'docker-maven' }

    stages {
        stage('Build') {
            steps {
                dir('apps/webbooks') {
                    sh "mvn -DskipTests clean package"
                }
            }

            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    // junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts '**/target/*.jar'
                }
            }
        }
    }
}
