version: '3.5'
services:
  jenkins-server:
    depends_on:
      - jenkins-docker
    image: ${DOCKER_REGISTRY}/jenkins-server:${JENKINS_VERSION}
    container_name: jenkins-server
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      JAVA_OPTS: "-Xms512m -Xmx1024m -Djenkins.install.runSetupWizard=false"
      # JAVA_OPTS: "-XX:MaxPermSize=512m -Xms512m -Xmx1024m -Djenkins.install.runSetupWizard=false"
      CASC_JENKINS_CONFIG: "/var/jenkins_home/casc_configs"
      JENKINS_ADMIN_ID: ${JENKINS_ADMIN_ID}
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD}
      JENKINS_URL: ${JENKINS_URL}
      DOCKER_HOST: tcp://jenkins-docker:2375
      DOCKER_CERT_PATH: ""
      DOCKER_TLS_VERIFY: ""
    secrets:
      - GITHUB_PAT
    volumes:
      - jenkins-data:/var/jenkins_home
      - /home/levelup/jenkins/casc_configs:/var/jenkins_home/casc_configs/
    networks:
      - jenkins-network
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    restart: unless-stopped
    ports:
      - 2375:2375
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-network

volumes:
  jenkins-data:

networks:
  jenkins-network:

secrets:
  GITHUB_PAT:
    file: /home/levelup/jenkins/github_pat